### ISSUE TITLE
grid is not working if tags appear

### ISSUE THREAD

**Issue by rohithpuchalapallialight** [primefaces/primeflex#105]
Grid not working if angular tags come in between. I need to create the grid dynamically.

```
<div class="grid">
    <aa>
        <div class="col-2">2</div>
        <div class="col-6">6</div>
        <div class="col-4">4</div>
    </aa>
</div>
```

**Comment by mertsincan** [comment]
Please try to use host: or @HostBinding('class') features to set classes to tag elements. 

Best Regards,
