### ISSUE TITLE
Boilerplate text on PrimeFlex documentation page

### ISSUE THREAD

**Issue by schambers** [primefaces/primeflex#106]
There is some boilerplate text on https://www.primefaces.org/primeflex/gridsystem

Under the "Grid System" header at the top of this page is this text that I'm assuming should be an intro:
`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`

**Comment by mycahmason** [comment]
Duplicate: https://github.com/primefaces/primeflex/issues/94
