### ISSUE TITLE
Add Pseudo-classes documentation

### ISSUE THREAD

**Issue by sneakylenny** [primefaces/primeflex#108]
### The issue
I've noticed documentation about the event handler classes (like `hover:`, `focus:` and `active:`) are missing or hard to find.
I expected it to be in the "Interactivity" section but the only place I could find `hover:` it is in the examples in the "Transition" category.

**Comment by melloware** [comment]
@TimVanHerwijnen care to submit a PR.  The whole showcase / docs are right in this github project.

**Comment by TimVanHerwijnen** [comment]
> care to submit a PR. 

I'm sorry to disappoint but I have no experience with ruby or jekyllrb and this project structure. 
So I won't be able to create a PR (for now) until I have time to learn about how it works.

**Comment by mertsincan** [comment]
We create sections with separate demos for pages with features that support these pseudo-classes. Perhaps in the future, these pseudo-classes can be documented as a separate page.
Exp; https://www.primefaces.org/primeflex/textcolor
