### ISSUE TITLE
Breakpoints variable cannot be overriden

### ISSUE THREAD

**Issue by Vilican** [primefaces/primeflex#111]
The `$breakpoints` variable in `_variables.scss` was not declared with `!default`, making it impossible to add custom breakpoints when `@use`-ing the library.

![Bug reproduction](https://user-images.githubusercontent.com/11300407/162594449-de7ed992-f9c3-4cbe-bf9e-e1ecbbd91d36.png)

**Comment by FKunz95** [comment]
I have already described the solution and the necessary adjustments in #52.
