### ISSUE TITLE
Cripples angular universal ssr performance

### ISSUE THREAD

**Issue by nitedani** [primefaces/primeflex#124]
Angular universal 13 introduced a feature called inlineCriticalCss. On ssr, it scans the document and inlines the css used by it. The more the css, the slower it is. 
![image](https://user-images.githubusercontent.com/67418286/169532346-a548fb0f-7090-429d-96a0-d3d430968607.png)
The scss imported for primeng + primeflex produces over 600kb of css. The result is, angular universal ssr takes from 150-800ms to run, on simple page with 3 cards. That is unacceptable for production. I purchased primeblocks for angular, but because it needs those large scss imports, I can't use it. After switching to tailwind, load times are much, much better. Tailwind eleminates the not needed css and it is not included in the production bundle. 
![image](https://user-images.githubusercontent.com/67418286/169533466-93cce5fc-2047-4e06-ad41-9e42fc2fedea.png)
I ask you to either switch over to tailwind and keep the library as a thin layer on tailwind, or implement unused css elimination just like tailwind did.

**Comment by nitedani** [comment]
Related: https://github.com/angular/universal/issues/2106

**Comment by vytautas-pranskunas-** [comment]
watching

**Comment by mertsincan** [comment]
Hi all,

https://www.primefaces.org/primeflex/setup
> Production Size
When using a utility CSS library like PrimeFlex, it is likely to use only a set of classes from the library leaving the rest of the library as unused. To avoid including the unused part from your application, it is strongly recommended to use a tool like [PurgeCSS](https://purgecss.com/) that analyzes your code and generates an optimized primeflex file that only contains the utilities you've used.

Best Regards,
