### ISSUE TITLE
Max width styles

### ISSUE THREAD

**Issue by Atomic71** [primefaces/primeflex#125]
In the documentation it says you can use the max-w-1rem, max-w-2rem...etc. But it's not possible in practice. Why I think that is because of the code in [_size.scss](https://github.com/primefaces/primeflex/blob/master/_sass/lib/src/_size.scss#L51-L55) only generates styles for the defined properties inside of this map, which does not contain 1,2,3,...25 rem.

**Comment by mertsincan** [comment]
Hi,

Please see `), 'max-w') !default;` line. We generate all max-w-*rem class using it. Also, could you please check it in primeflex.css file?

Best Regards,
