### ISSUE TITLE
Gap has no effect / is not working

### ISSUE THREAD

**Issue by Wasserwecken** [primefaces/primeflex#127]
### I want to use the gap classes
https://www.primefaces.org/primeflex/gap

### Problem:
- Using either of this classes will have no effect at all.
- Using the exact examples in the documentation do not work as well.

### Expected:
- Having gaps between the elements.

### Material / Examples:
Minimal example with the first code block in the documentation:
https://jsfiddle.net/pLmc7g38/

The code again for the minimal example:
```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://unpkg.com/primeflex@3.1.2/primeflex.css">
    <link rel="stylesheet" href="https://unpkg.com/primeflex/themes/vela-blue.css">
  </head>
  <body>
    <div class="card">
        <div class="flex flex-wrap justify-content-center card-container blue-container gap-3">
            <div class="border-round w-12rem h-6rem bg-blue-500 text-white font-bold flex align-items-center justify-content-center">1</div>
            <div class="border-round w-12rem h-6rem bg-blue-500 text-white font-bold flex align-items-center justify-content-center">2</div>
            <div class="border-round w-12rem h-6rem bg-blue-500 text-white font-bold flex align-items-center justify-content-center">3</div>
            <div class="border-round w-12rem h-6rem bg-blue-500 text-white font-bold flex align-items-center justify-content-center">4</div>
        </div>
    </div>
  </body>
</html>
```

The result in my Browser (Chrome 101.0.4951.67):
![image](https://user-images.githubusercontent.com/15609168/170441960-d74ad726-a3e9-42fb-a979-2e41aa001c4e.png)

**Comment by mertsincan** [comment]
Please use PrimeFlex 3.2.0.

Best Regards,

**Comment by Wasserwecken** [comment]
Version 3.2.0 solves the problem. Thanks!

Please update then the documentation section: "Load from CDN":
https://www.primefaces.org/primeflex/setup
