### ISSUE TITLE
gap not working

### ISSUE THREAD

**Issue by guhyeon** [primefaces/primeflex#129]
I have copied example on https://www.primefaces.org/primeflex/gap

![image](https://user-images.githubusercontent.com/9765614/172061766-9dbe80d4-4f72-4e80-bb67-fbaf578da8a9.png)

pasted to myproject and it looks 
![image](https://user-images.githubusercontent.com/9765614/172061761-16d4c408-a28a-40cf-9f81-bb4c7f7f7bff.png)

I'd used primeflex version 3.1.2

and there are no gap css class in primeflex.css

**Comment by melloware** [comment]
Do you mean 3.1.2 or 3.2.1 ?

**Comment by mertsincan** [comment]
Yes, you need to use v3.2.1 for this feature.
