### ISSUE TITLE
Document and define the new $prefix variable

### ISSUE THREAD

**Issue by grizzlydev-sarl** [primefaces/primeflex#131]
Introduced in 442adc1 because of #110
The new $prefix variable is curently undefined, and compilation fails.

Primeflex v3.2.1

```
./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
1 │ .#{$prefix}grid {
  │    ^^^^^^^
  ╵
  node_modules/primeflex/src/_grid.scss 1:4  @import
```

Could you please define the variable with an empty value and document it.
Thanks in advance.
Cheers.

**Comment by mertsincan** [comment]
Hi,

it has already been defined.
https://github.com/primefaces/primeflex/blob/master/_sass/lib/src/_variables.scss

Could you please attach your scss imports?

**Comment by grizzlydev-sarl** [comment]
Oh, snap! You're right!
I had completely forgotten that I had made some tweaks with my imports.

Thanks for the quick reply.
And sorry for the noise.

**Comment by mertsincan** [comment]
No worries ;) Thanks a lot for your update!

Best Regards,
