### ISSUE TITLE
grid-flow and col-span don't work with responsive

### ISSUE THREAD

**Issue by safejace** [primefaces/primeflex#132]
as reported on discord: https://discord.com/channels/787967399105134612/787968902058999818/994634667452022795

`md:grid-columns-4` is overriding `lg:grid-columns-3` on large screens?

my window is over `992px` wide. but the medium class is taking precedence

same issue with col-spa

![](https://cdn.discordapp.com/attachments/787968902058999818/994634666722209842/unknown.png)
n

whereas if i put text-{size} it works as expected

![](https://cdn.discordapp.com/attachments/787968902058999818/994639104262287400/unknown.png)

![](https://cdn.discordapp.com/attachments/787968902058999818/994639104509755493/unknown.png)

**Comment by mertsincan** [comment]
Hi @safejace,

Currently, these classes are not available in primeflex. I guess they come from a different library.

Best Regards,
