### ISSUE TITLE
"gap"-classes missing

### ISSUE THREAD

**Issue by agnyp** [primefaces/primeflex#133]
I have version 3.1.3 installed and it seems that all classes regarding "gap", like "row-gap-3" are missing.
None of the classes listed [here](https://www.primefaces.org/primeflex/gap) are available.

**Comment by melloware** [comment]
Did you try upgrading to the latest 3.2.1 ?

**Comment by agnyp** [comment]
> 

Ah, thought to have the latest version. Will try right away.

**Comment by agnyp** [comment]
Much better, thanks! (Will look next time. It's right there on the main page. 🤦 )
