### ISSUE TITLE
Multiple properties in responsive

### ISSUE THREAD

**Issue by World3Developer** [primefaces/primeflex#149]
Is posible to do something like this?  It only get the first class of the col-6

```

<div class="footer">

    <div class="grid max-width">

        <div class="col-12 text-left p-5 md:col-6 text-center">
            <img src="assets/images/logo-white.png" height="20">
        </div>
        <div class="col-12 text-right text-white p-5 md:col-6 text-center">
            Privacy Policy | Terms and Conditions | Risks
        </div>

    </div>

</div>

```

I want when I change to md size, it gets col-6 AND text-center.

Thanks

**Comment by atakantepe** [comment]
It appears you may have a slight misconception about how these classes work in responsive design. The class md:col-6 will apply the col-6 styling starting at the md breakpoint and above, not just at the md size. If you want different column sizes for different screen widths, you can chain classes as follows: col-12 sm:col-6 md:col-4 lg:col-3. Here's how it works:

For screens smaller than sm, col-12 will be applied.
For screens larger than sm but smaller than md, col-6 will be applied.
For screens larger than md but smaller than lg, col-4 will be applied.
For screens larger than lg, col-3 will be applied.

The same principle applies to your text alignment classes.

I hope this clears up any confusion. These classes allow you to control the layout and styling of your elements at different viewport sizes, providing a responsive design for your site.

**Comment by certifirm** [comment]
The question is if you can apply styles like this:

<div class="col-12 text-left p-5 md:col-6 text-center">

In col 12, text-left and p-5.  Then in col-6, text-center and default padding.
