### ISSUE TITLE
[Docs] Issue with documentation

### ISSUE THREAD

**Issue by tomavic** [primefaces/primeflex#163]
Hi all

What is the difference between 
https://www.primefaces.org/primeflex/display

and 

https://primeflex.org/placement

Thanks for your efforts. Really appreciated

**Comment by atakantepe** [comment]
Hi there!

Thanks for reaching out and for your kind words. However, I'm a bit unclear on your question. The page at https://www.primefaces.org/primeflex/display provides details on CSS display classes, while https://primeflex.org/placement is about positional utilities for top, bottom, left, and right placements.

Could you please clarify what specific differences you're asking about? I'd be glad to assist further!

**Comment by tomavic** [comment]
Thanks @atakantepe 

It's my bad, I mean the url itself 

<img width="1127" alt="Screenshot 2023-06-02 at 12 09 04 PM" src="https://github.com/primefaces/primeflex/assets/17650005/aa4b0dd6-5dde-4707-b6c6-9f820d62aea7">


<img width="1213" alt="Screenshot 2023-06-02 at 12 08 47 PM" src="https://github.com/primefaces/primeflex/assets/17650005/80e371cc-bd86-44f2-9427-260a8dc67cea">


Why there are two version of the documentation?

BTW, I prefer the old one, because it allows me to select the attribute class with one click.

**Comment by atakantepe** [comment]
> 

Hi, I fixed the issue with a one-click to select attributes. The old one will be directed to the new one. With 4.0, primeflex will have many more features like config to customize it. I hope you like it 🚀

**Comment by tomavic** [comment]
Well done @atakantepe
