### ISSUE TITLE
Fix Align Self Docs

### ISSUE THREAD

**Issue by reksaandhika** [primefaces/primeflex#173]
Currently **Align Self** classes docs using **Align Items** classes

Link: [https://primeflex.org/alignself](https://primeflex.org/alignself)

![image](https://github.com/primefaces/primeflex/assets/39384007/5edeaa44-0caf-4ab6-8b40-2483c0ff08ce)

**Comment by melloware** [comment]
Duplicate of https://github.com/primefaces/primeflex/issues/165

**Comment by reksaandhika** [comment]
> Duplicate of #165

Oh didn't notice that, thanks for the mention
