### ISSUE TITLE
negative margin left and right often leads to a horizontal scrollbar

### ISSUE THREAD

**Issue by yennor** [primefaces/primeflex#18]
I've tried to use the p-grid class inside of several containers.
It happens often, that then a horizontal scrollbar will be displayed.
Even if you use it in a full screen container like:
```

 	<h:body>
 		<div class="p-grid">
  ...

``` 

I'm way no css specialist, designer, or anything similar, but is there any reason why you set:

>   margin-right: -0.5em;
>   margin-left: -0.5em;
>   margin-top: -0.5em;

When I disable the left and right margins the hoirzontal scrollbars disappear, and it also doesn't destroy anymore the design from the contrainer component. With those negative margins, it's usually to near to the border of the container component.

**Comment by 73k70n** [comment]
I encountered this too. Disabling those negative margins does make it a lot better IMHO.

**Comment by josesalasni** [comment]
Yeah same here. I had to use 
.p-grid {
  margin-left: 0;
  margin-right: 0;
  margin-top: 0;
}
 
for now, I not have been problems using it. You can also disable the horizontal scroll if necessary.

**Comment by yennor** [comment]
I'm not sure if those negative margin were meant to somehow be used, to space properly between child elements of the flexbox (i've seen some people using that negative trick).
anyway. Since I've wanted to have spacing between the child element of the flexboxes with none negative margins I've added following:

.p-grid:not(.p-dir-col) > * + * {
  margin-left: 0.5em;
}

.p-dir-col > * + * {
  margin-top: 0.5em;
}

this adds the margins to all child elements besides the first one.

**Comment by cagataycivici** [comment]
There is built-in p-nogutter to remove the negative spacing.

```
<div class="p-grid p-nogutter
```

More info about negative margin trick;

https://medium.com/@justintulk/why-css-grid-frameworks-have-negative-margins-37d67cf6acc8
