### ISSUE TITLE
"p-dir-col" not properly rendered in IE11

### ISSUE THREAD

**Issue by AlainD-** [primefaces/primeflex#2]
Hi,
The columns alignment using "p-dir-col" does not display as expected in IE11.

To reproduce, check out the demo page opened in Internet Explorer 11:
https://www.primefaces.org/primeng/#/flexgrid

=> There are no space between each row in IE, while the columns are correctly displayed in Chrome for instance.

![primeflex-issue-in-ie-with-p-dir-col](https://user-images.githubusercontent.com/5165564/45776028-ed099080-bc51-11e8-91fc-2d6f28abceed.png)
![primeflex-ok-in-chrome-with-p-dir-col](https://user-images.githubusercontent.com/5165564/45776034-f3980800-bc51-11e8-9157-d8b3fe210324.png)

**Comment by DineshSPatil** [comment]
any updates on this?

**Comment by MrBogue** [comment]
+1
