### ISSUE TITLE
there is missing p-xl class that would be like p-col

### ISSUE THREAD

**Issue by godfryd** [primefaces/primeflex#20]
I would like to use the following classes for my element: class="p-col-12 p-xl",so 
1. on mobile the element takes whole width 
2. but in case of desktop it takes proportional width with other elements in p-grid row. 

It appears that p-xl, p-lg, p-md and p-sm are not defined.

**Comment by cagataycivici** [comment]
I could not understand the use case, what should be the value of p-xl? Please elaborate #2.

**Comment by godfryd** [comment]
Example: I have 7 elements in a row. In case of mobile each of them should take 100% width
so they are one below another (ie. one takes whole row actually).
In case of desktop I want to fit them in one row so each of them takes 1/7 of 100% width.
For that I would use p-col but this is for mobile only, for desktop I should use p-xl, p-lg, etc.
But they are not defined.

p-xl, p-lg, p-md, p-sm would be defined in similar way as p-col ie. with flex-grow: 1.
