### ISSUE TITLE
Is this repository still actively maintained?

### ISSUE THREAD

**Issue by antham** [primefaces/primeflex#219]
Hi there,
It seems there are several PR/issues (almost all?) not answered/managed.
The last commit is 5 months old and the last release almost 1 year old.
So just wondering if this repository is actively maintained?

**Comment by JohnnyWalkerDigital** [comment]
The oldest PR is nearly a year old :-/

**Comment by melloware** [comment]
PrimeTek announced somewhere they are going to standardize on TailWind CSS instead of maintaining PrimeFlex for the JS libs.  

I would still like to see them release a final 4.0.0 version of PrimeFlex with whatever they have.

**Comment by ivan-price-acted** [comment]
indeed:
https://primevue.org/guides/primeflex/
