### ISSUE TITLE
Responsive: Allow '0' to hide elements

### ISSUE THREAD

**Issue by melloware** [primefaces/primeflex#24]
**Description**
Sometimes, I'd like a component (or simply a div) to be shown only on desktop. I'd like it to disappear (at least visually) on mobile, and vice-versa.

Originally reported in Primefaces: https://github.com/primefaces/primefaces/issues/6098

Consider [this social login example](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_social_login), I'd like to show:

- "**Or sign in manually:**" on mobile only (e.g., through a hypothetical `<div class="ui-g-12 ui-md-0 ui-lg-0"/>`
- "**Or:**" on desktop only (e.g., through a hypothetical `<div class="ui-g-0 ui-md-2 ui-lg-2"/>`

**Comment by cagataycivici** [comment]
We have display utilities for this so I rather not duplicate the functionality, please review;

https://primefaces.org/primeng/showcase/#/primeflex/display
