### ISSUE TITLE
Not working in Angular

### ISSUE THREAD

**Issue by HenriquePereiraRosa** [primefaces/primeflex#3]
I couldn't make the PimeFlex work in my project.

- Command to install:
`npm install primeflex --save`

After that the folder was installed perfectly in "node_modules" and save in "package.json":

`"primeflex": "^1.0.0-rc.1",`

- I'm trying to use in my .html but is not working:

 ` <div class="container">
  <div class="p-grid">
    <div class="p-col-12">
      <h1 class="title">Dashboard - AR CONDICIONADO</h1>
    </div>

    <div class="p-grid">
      <div class="p-col-12 p-md-4">
        <div class="box">
          <p-card>
            <h4>Corrente: {{sensor?.current}}A</h4>
          </p-card>
        </div>
      </div>

      <div class="p-col-12 p-md-4">
        <div class="box">
          <p-card>
            Temperatura: {{sensor?.temperature}}ºC
          </p-card>

          <p-card>
            Umidade: {{sensor?.humidity}}%
          </p-card>

          <p-card>
            Bateria: {{sensor?.vBat}}V
          </p-card>
        </div>
      </div>

      <div class="p-col-12 p-md-4">
        <div class="box">
          <p-card>
            <div>Status: </div>
            <br>
            <div *ngIf="getAnomaly(); then true_content else false_content"></div>
            <ng-template #true_content><img width='20%' src="../../../assets/img/status_icons/error_red.png"></ng-template>
            <ng-template #false_content><img width='20%' src="../../../assets/img/status_icons/ok_green.jpg"></ng-template>
          </p-card>
        </div>
      </div>
    </div>

    <div class="p-col-12 p-md-12">
      <div class="margin">
        <h4>Valores no eixo X: {{requestNumber}}</h4>
        <p-slider [(ngModel)]="requestNumber" (onSlideEnd)="handleChange($event)" [step]="20" [min]="10" max="2000"
          [style]="{'width':'100%'}"></p-slider>
      </div>
    </div>

    <div class="p-col-12 p-md-12">
      <p-panel header="Corrente">
        <p-chart type="line" [data]="lineChartData" [options]="options"></p-chart>
      </p-panel>
    </div>

    <div class="p-col-12 p-md-12">
      <p-panel header="Diferença de Temperatura Interna e Externa">
        <p-chart type="bar" [data]="barChartData" [options]="options"></p-chart>
      </p-panel>
    </div>

  </div>
</div> `    

result: 
 
![image](https://user-images.githubusercontent.com/16025104/45931221-48cd6580-bf41-11e8-8f99-93dfdf1f51f1.png)

I've tryied diverses combinations but none of primeflex has done effect. The result is always the same as the pic.

**Comment by m-git-hub** [comment]
I had the same problem. After adding the "node_modules/primeflex/primeflex.css" file into the project solved my problem.
Try with same thing, hope it helps to you.

**Comment by HenriquePereiraRosa** [comment]
Is there already:

![image](https://user-images.githubusercontent.com/16025104/45963415-8261a780-bff9-11e8-827d-bf6950d7b175.png)

Right?

**Comment by HenriquePereiraRosa** [comment]
It's working... I think is the missing declaration in angular.json. Now started to work. Thanks!
