### ISSUE TITLE
Deprecate Grid CSS flex props in favor of FlexBox

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeflex#32]
The new flexbox utility makes a couple of grid css properties obselete;

- p-justify
- p-align
- p-col-align
- p-dir
- p-col-order

As they have more flexible counterparts in flexbox.

**Comment by alejandrocoding** [comment]
Hi!

I have been researching the doc and SO but haven't found anything, sorry if I missed it somewhere.
Can I ask why p-flex adds flex layout but p-grid (instead of adding grid layout) adds flex layout too?

Thanks!
