### ISSUE TITLE
PrimeFlex cannot be used with Bootstrap together

### ISSUE THREAD

**Issue by havist** [primefaces/primeflex#35]
Since the PrimeFlex is using `p-sm-*`, `p-md-*`, `p-lg-*` and `p-xl-*` selectors for its grid system it cannot be used together with Bootstrap because of collision with [Bootstrap's Spacing utility](https://getbootstrap.com/docs/4.0/utilities/spacing/). It uses those selectors as well but for spacing purposes.
The fix can be made by renaming all the PrimeFlex's grid selectors to `p-col-*`.

**Comment by han2015** [comment]
The worse is that the grid breaks a "common define-rule" of PrimeFlex.
a common rule of it looks like `p-{property}-{breakpoint}-{value}`.
```
eg. p-d-xl-block, p-flex-column, p-flex-md-column, 
  p-mb-md-0(margin) , p-p-lg-3(padding)
```

but the **grid** spec with breakpoints, it looks like below. obviously, it could be `p-col-{breakpoint}-{value}`
```
p-sm-* | p-sm-6, p-sm-4
p-md-* | p-md-2, p-md-8
```
Also, the **offset** spec, it could be `p-offset-{breakpoint}-{value}`. But...
```
p-sm-offset-* | p-sm-offset-6, p-sm-offset-4
p-md-offset-* | p-md-offset-6, p-md-offset-4
p-lg-offset-* | p-lg-offset-6, p-lg-offset-4

```

**Comment by bwermes** [comment]
As best I can tell, PrimeFlex V3 is not intended to even work with PrimeNG V12 (rc1) as the differences in grid class names did not ripple to PrimeNG.

**Comment by mertsincan** [comment]
Hi,

You can override $prefix variable for this issue. Default value is ''.

Best Regards,

**Comment by adrian-stroe** [comment]
Does overriding $prefix mean changing the class names from inside of the primeflex.css file ?
