### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by JMaylor** [primefaces/primeflex#37]
In the docs for primevue primeflex, there is a typo.

[https://primefaces.org/primevue/showcase/#/primeflex](https://primefaces.org/primevue/showcase/#/primeflex)

In the section describing how to import only certain CSS files, there is a typo - formlayou**r** should be formlayou**t**

```
import 'primeflex/src/_formlayour.css';
```

**Comment by onursenture** [comment]
Fixed 9a43ebdb02a23b6df3b65032ba636652239629e6, thanks.
