### ISSUE TITLE
SCSS Variable override not working

### ISSUE THREAD

**Issue by vdbongard** [primefaces/primeflex#47]
I have followed the setup steps for overwriting SCSS variables from: https://primefaces.org/primeng/showcase/#/primeflex

The problem I have is that the variables in `_overrides.scss` are not overriding the PrimeFlex SCSS Variables.

I created a StackBlitz project to reproduce the issue: https://stackblitz.com/edit/bug-primeflex-scss-variable-overrides

As you can see the button has different padding styles for different breakpoints.
The breakpoints however are the default ones and not the ones from the `_overrides.scss`.

At first I tried to import the styles exactly like in the documentation but then I ran into another issue which might be related to this: https://github.com/primefaces/primeflex/issues/38

**Comment by danini-the-panini** [comment]
Can confirm, this is not just a primeng problem, I am facing the same issue in primevue.

I believe the problem lies in the way the breakpoint variables are defined, I've made a suggestion here: #64

**Comment by MariiaPolova** [comment]
Ay updates on this?

**Comment by Branka89** [comment]
Hi guys, 
in Primeflex docs, variable $lg (Breakpoint of screens such as notebook monitors) has a default value of 992px. How can I change that? For example, I want to set a default value of 1100px. Please assist 🙂 I'm using Primeflex 3.0.1

**Comment by mertsincan** [comment]
Please see https://github.com/primefaces/primeflex/issues/52#issuecomment-1069096707

Best Regards,
