### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/primeflex.css.map"

### ISSUE THREAD

**Issue by folamy** [primefaces/primeflex#49]
It works fine, but I am getting Vue-Router warning about path to primeflex.css.map on the server. And this
"DevTools failed to load SourceMap: Could not parse content for http://localhost:3000/primeflex.css.map: Unexpected token < in JSON at position 0' on the browser console.
What could have caused this, and how do I get rid of it?

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeflex/issues/72
