### ISSUE TITLE
Make more use of mixins to allow for easier extention

### ISSUE THREAD

**Issue by Dedme** [primefaces/primeflex#51]
I have come from Clarity UI,  and the way they had set up their SCSS while fairly complex also automates a lot of the extension work between each of the various breakpoints.

https://github.com/vmware/clarity/tree/next/packages/angular/projects/clr-angular/src/layout/grid/mixins

this allows to simply extend the breakpoints list and add new ones or update existing, and all values are worked out.
if something like this could be implemented that would greatly enable the use of more breakpoints across the system.
and remove issues with missing utilities for some breakpoints.

**Comment by mertsincan** [comment]
Please see https://github.com/primefaces/primeflex/issues/52#issuecomment-1069096707

Best Regards,
