### ISSUE TITLE
Add additional breakpoints

### ISSUE THREAD

**Issue by andrew-simmons** [primefaces/primeflex#52]
## Issue
Currently my team uses displays that are 3440px wide. It would be helpful to have another one or two breakpoints (eg. 2x & 3x) to cover the gap between 1200px and 3440px.

## Current Breakpoints
```
p-sm-* : min-width 576px
p-md-* : min-width 768px
p-lg-* : min-width 992px
p-xl-* : min-width 1200px
```

**Comment by Manuel-Moya** [comment]
I miss the extra small and xxl breakpoints.

**Comment by Dedme** [comment]
yes, with so many wide screens I like a 1400, 1600 breakpoint, and really don't want to have to roll my own to manage it.
would be great to see it writen with a more dynamic definition to enable simple extension of custom breakpoints (and columns)

migrating to a mix-in style of definition would make both the code cleaner and extension simpler.
https://www.sitepoint.com/managing-responsive-breakpoints-sass/

**Comment by danini-the-panini** [comment]
I've made a suggestion which might solve the problem: #64

**Comment by gpolcode** [comment]
@cagataycivici is there any update on this? there is a full solution provided in #64

**Comment by Hydhen** [comment]
Would be even better to be able to setup custom breakpoints

**Comment by FKunz95** [comment]
To override and set up custom breakpoints, the `_variables.scss` should be changed as follows:

```
$sm:576px !default;
$md:768px !default;
$lg:992px !default;
$xl:1200px !default;

$breakpoints: (
    'sm': $sm,
    'md': $md,
    'lg': $lg,
    'xl': $xl
) !default;
```

Then you can override and set up custom breakpoints in your own `variables.scss` as follows:

```
$sm:576px;
$md:768px;
$lg:992px;
$xl:1300px;
$xxl:2000px;

$breakpoints: (
    'sm': $sm,
    'md': $md,
    'lg': $lg,
    'xl': $xl
    'xxl': $xxl
)
```

**Comment by Hydhen** [comment]
> To override and set up custom breakpoints, the `_variables.scss` should be changed as follows:
> 
> ```
> $sm:576px !default;
> $md:768px !default;
> $lg:992px !default;
> $xl:1200px !default;
> 
> $breakpoints: (
>     'sm': $sm,
>     'md': $md,
>     'lg': $lg,
>     'xl': $xl
> ) !default;
> ```
> 
> Then you can override and set up custom breakpoints in your own `variables.scss` as follows:
> 
> ```
> $sm:576px;
> $md:768px;
> $lg:992px;
> $xl:1300px;
> $xxl:2000px;
> 
> $breakpoints: (
>     'sm': $sm,
>     'md': $md,
>     'lg': $lg,
>     'xl': $xl
>     'xxl': $xxl
> )
> ```

Are the new declared breakpoints usable in template as sugar as below ?

```
<div class="md:col-12 lg:col-4 xl:col-2 xxl:col-1"></div>
```

**Comment by FKunz95** [comment]
> Are the new declared breakpoints usable in template as sugar as below ?
> 
> ```
> <div class="md:col-12 lg:col-4 xl:col-2 xxl:col-1"></div>
> ```

Yes, in my local tests it worked.

**Comment by mertsincan** [comment]
To add new breakpoints, you can override $breakpoints variable after the next version is released.

Best Regards,

**Comment by choff5507** [comment]
I followed this post exactly and cannot get a `xs` breakpoint implemented. No idea why. Is this still how you do it in the most current version of PrimeVue/PrimeFlex?

**Comment by neldrak** [comment]
Also not working for me.
Would be cool to know which version this is/will be included in and how to actually use it.
Thanks!

**Comment by neldrak** [comment]
I realized that _grid.scss is not part of the theme designer, so you can't just override it.
I check the latest theme designer packages and can't find it in any setup/theme.

**Comment by alperari** [comment]
> To override and set up custom breakpoints, the `_variables.scss` should be changed as follows:
> 
> ```
> $sm:576px !default;
> $md:768px !default;
> $lg:992px !default;
> $xl:1200px !default;
> 
> $breakpoints: (
>     'sm': $sm,
>     'md': $md,
>     'lg': $lg,
>     'xl': $xl
> ) !default;
> ```
> 
> Then you can override and set up custom breakpoints in your own `variables.scss` as follows:
> 
> ```
> $sm:576px;
> $md:768px;
> $lg:992px;
> $xl:1300px;
> $xxl:2000px;
> 
> $breakpoints: (
>     'sm': $sm,
>     'md': $md,
>     'lg': $lg,
>     'xl': $xl
>     'xxl': $xxl
> )
> ```

Worked for me after adding the line

```scss
@import 'primeflex/primeflex.scss';
```

to the end of `_variables.css`
