### ISSUE TITLE
Add additional columns

### ISSUE THREAD

**Issue by andrew-simmons** [primefaces/primeflex#53]
## Issue
My team is using primeflex to layout our page content into 3 or 4 columns that is responsive across all of the breakpoints. With only 12 columns, the 4 column layout makes some compromises to be responsive. See example below.

Would like to have a 24 column layout (or additional half size col and offset classes) for additional flexibility in sizing logical columns across several breakpoints. 

### 12 col layout
```
col4_1 = p-col-12 p-sm-3 p-md-3 p-lg-2 p-xl-1
col4_2 = p-col-12 p-sm-6 p-md-6 p-lg-4 p-xl-2
col4_3 = p-col-12 p-sm-9 p-md-9 p-lg-6 p-xl-3
col4_4 = p-col-12 p-sm-12 p-md-12 p-lg-8 p-xl-4

offset4_0 = p-offset-0 p-sm-offset-0 p-md-offset-0 p-lg-offset-4 p-xl-offset-8
offset4_1 = p-offset-0 p-sm-offset-3 p-md-offset-3 p-lg-offset-6 p-xl-offset-9
offset4_2 = p-offset-0 p-sm-offset-6 p-md-offset-6 p-lg-offset-8 p-xl-offset-10
offset4_3 = p-offset-0 p-sm-offset-9 p-md-offset-9 p-lg-offset-10 p-xl-offset-11
```
* sm and md columns are the same size
* xl can be pretty narrow near it's breakpoint with lg

### 24 col layout
```
col4_1 = p-col-12 p-sm-6 p-md-5 p-lg-4 p-xl-3 p-2x-2 p-3x-1
```
* sm and md columns are different sizes
* xl is slightly larger (1.5x)
* There's room for additional future breakpoints

**Comment by cagataycivici** [comment]
Thank you, right now we'll stay on 12, if there is more demand, we'll add 24 columns for sure. Thank you for the feedback.
