### ISSUE TITLE
Placeholder documentation for User Select

### ISSUE THREAD

**Issue by stolp** [primefaces/primeflex#57]
Looking at [https://www.primefaces.org/primeflex/userselect](https://www.primefaces.org/primeflex/userselect) I find a lot of `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`

I think this documentation page has not yet been finished.

**Comment by cagataycivici** [comment]
Added missing text, thank you.
