### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by Dedme** [primefaces/primeflex#58]
did a sweeping update of my packages, updated to version 3, but seems to have dropped all the p- tags?!?
1 this is a huge amount of fixing, but 2 there seems to be no documentation on this change?

primeng documentation says to install latest, but has code examples with p-.

**Comment by PeterHewat** [comment]
Indeed, I noticed this as well. Very confused about this and what to do without any documentation/info.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot! Migration Guide: https://www.primefaces.org/primeflex/migration

Best Regards,

**Comment by Dedme** [comment]
sorry @mertsincan, but is there any online reference for those still using 2.x?

**Comment by cagataycivici** [comment]
You can use the PrimeFlex docs from v10;

https://www.primefaces.org/primeng/v10-lts/#/
