### ISSUE TITLE
In v3.0.0 horizontal of p-col breaks. 

### ISSUE THREAD

**Issue by mnjaya** [primefaces/primeflex#59]
Below Example code also gives p-cols folded over with 100% width. 
```
<div class="p-grid">
    <div class="p-col">
        <div class="box">1</div>
    </div>
    <div class="p-col">
        <div class="box">2</div>
    </div>
    <div class="p-col">
        <div class="box">3</div>
    </div>
</div>
```
Observed in multiple sites with similar behaviour. 
Changed back to v.2.0.0 and it is normal. So please check the v3.0.0 for the unexpected behaviour.

**Comment by melloware** [comment]
@mnjaya please see the migration guide.  The "p" is no longer valid: https://www.primefaces.org/primeflex/migration

**Comment by mnjaya** [comment]
Sincere Apologies…..
I missed it. Sorry.

Thanks much.

**Comment by melloware** [comment]
I think its safe to close this ticket...

**Comment by mnjaya** [comment]
The "p" is no longer valid: https://www.primefaces.org/primeflex/migration.
May be it will help many like me.....
Closed
