### ISSUE TITLE
css is not getting imported in vue 3

### ISSUE THREAD

**Issue by maximegheraille** [primefaces/primeflex#60]
Hi,

When installing and using primeflex, the classes are not working. These were my steps.

I followed the described steps from the [documentation](https://www.primefaces.org/primevue/showcase/#/primeflex).

The css is indeed inside the node_modules

![Capture](https://user-images.githubusercontent.com/32335849/126332707-c2aa3fe5-c7f1-4ba7-91dc-1fc89668a833.PNG)

Imported the css like this `import "primeflex/primeflex.css";` inside my main.ts

When looking at a simple div with `p-d-flex` the chrome dev tools shows that the class is not getting used.

![Capture2](https://user-images.githubusercontent.com/32335849/126333374-07f3c74b-2fe4-401c-b0f5-add5aeca4935.PNG)

my packages.json

```
  "dependencies": {
    "core-js": "^3.6.5",
    "primeflex": "^3.0.0",
    "primeicons": "^4.1.0",
    "primevue": "^3.5.1",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  }
```

**Comment by Papipone** [comment]
Same problem here

**Comment by maximegheraille** [comment]
@Papipone thank you for pointing that. It seems the right documentation is on https://www.primefaces.org/primeflex
 and not on https://www.primefaces.org/primevue/showcase/#/primeflex
