### ISSUE TITLE
2.x documentation missing?

### ISSUE THREAD

**Issue by nicholas-ochoa** [primefaces/primeflex#61]
Is there a reference to the 2.x documentation somewhere? It looks like it was removed entirely from the PrimeFlex docs as well as the PrimeNG docs.

**Comment by jesuspa17** [comment]
+1

**Comment by DazDotOne** [comment]
I'd also add that the primevue docs seem to still reference v2 primeflex docs

https://primefaces.org/primevue/showcase/#/grid

I'm completely new to primefaces and this had me scratching my head for a while.

**Comment by bmarvinb** [comment]
+1

**Comment by Dedme** [comment]
this is the best someone could offer me: https://www.primefaces.org/primeng/v10-lts/#/
but INSANE they would make such a large change and blow away existing documentation!!?!?!

**Comment by bgl3317** [comment]
The 2.0 documentation was blown away without warning? We're just all supposed to instantly upgrade at the drop of a hat? Who in the world thought this was a good idea?

**Comment by psarno** [comment]
I went to the PrimeFlex site as normal to refresh my brain on the form layout classes, and nothing was working.

Upgrading to PrimeFlex 3.0 completely demolished my site layout, so that's not an option.

We need the 2.0 documentation!

**Comment by taxpayer** [comment]
Hey guys, looks like v2.0 documentation is showing again on the showcase page:
https://www.primefaces.org/primeng/showcase/#/

![image](https://user-images.githubusercontent.com/9285710/128548022-e3ee8863-a68b-45e5-b468-02742dd49c18.png)

**Comment by cagataycivici** [comment]
You can blame me for the bad decision, It is back now though.

**Comment by psarno** [comment]
@cagataycivici Is the PrimeFlex 2.0 documentation gone again?

I can't find any reference to it on the website, just a link to the current one (3.0 I assume).

**Comment by Mettbrot** [comment]
Yes, I can't seem to find the documentation either :(

**Comment by zufra** [comment]
Here is the doc: https://github.com/primefaces/primeflex/wiki/PrimeFlex-v2
