### ISSUE TITLE
SassError: Expected identifier

### ISSUE THREAD

**Issue by gkrit** [primefaces/primeflex#91]
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
**SassError: Expected identifier.**
   ╷
27 │         .text-blue #2196F3{
   │                     ^
   ╵
  node_modules\primeflex\src\_**mixins.scss 27:21**  color-class()
  node_modules\primeflex\src\_colors.scss 11:1   @import
  node_modules\primeflex\primeflex.scss 4:9      @import
.................

**Comment by cagataycivici** [comment]
I'm not able to replicate, can you please try with the latest version?

**Comment by mertsincan** [comment]
I have tagged this issue as "Fixed" for now. If a new update comes from your side, please reopen this ticket. Thanks a lot for your understanding!
Best Regards,

**Comment by gkrit** [comment]
Hi

I am using the barcelona premium template.
You can replicate the error by using in the styles.scss the folowing

/* You can add global styles to this file, and also import other style files */

@import 'primeng/resources/primeng.min.css';
@import 'assets/theme/theme-blue-grey.scss';
@import 'primeflex/primeflex.scss';
@import 'primeicons/primeicons.css';

if i change the third line regarding primeflex
@import 'primeflex/primeflex.css';
then everything works ok


Is this an error from the premium template or from the primeflex library ?
I need to customize some things from primeflex so i need to import the scss file.

Sorry for the late response.

**Comment by rui-leite-ndrive** [comment]
> Hi
> 
> I am using the barcelona premium template. You can replicate the error by using in the styles.scss the folowing
> 
> /* You can add global styles to this file, and also import other style files */
> 
> @import 'primeng/resources/primeng.min.css'; @import 'assets/theme/theme-blue-grey.scss'; @import 'primeflex/primeflex.scss'; @import 'primeicons/primeicons.css';
> 
> if i change the third line regarding primeflex @import 'primeflex/primeflex.css'; then everything works ok
> 
> Is this an error from the premium template or from the primeflex library ? I need to customize some things from primeflex so i need to import the scss file.
> 
> Sorry for the late response.

Hi,

I am using PrimeFlex@3.2.0 and PrimeNG@13.4.0.

If I import PrimeFlex on a Angular component style, everything is ok. But if I import PrimeFlex on a global style file, using the `@import 'primeflex/primeflex.scss'; statement, the error occurs.

I tried this on Angular 12 and Angular 13 and the error is the same.

```
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
71 │         .text-blue #007bff{
   │                     ^
   ╵
  node_modules/primeflex/src/_mixins.scss 71:21  color-class()
  node_modules/primeflex/src/_colors.scss 11:1   @import
  node_modules/primeflex/primeflex.scss 4:9      @import
```

**Comment by gkrit** [comment]
@rui-leite-ndrive it's the same error as intially reported.
@mertsincan i think we should re open it.

**Comment by pasevin** [comment]
Experiencing the same issue.

**Comment by mertsincan** [comment]
I'll check and get back to you.

**Comment by pasevin** [comment]
The issue was introduced with `v3.1.0`

**Comment by mertsincan** [comment]
Hi all,

Could you please try the following;
```
/* You can add global styles to this file, and also import other style files */
@forward 'assets/theme/theme-blue-grey.scss' hide $colors;
@import 'primeng/resources/primeng.min.css';
@import 'primeflex/primeflex.scss';
@import 'primeicons/primeicons.css';

/* your other imports */
...
```

**Comment by pasevin** [comment]
> Hi all,
> 
> Could you please try the following;
> 
> ```
> /* You can add global styles to this file, and also import other style files */
> @forward 'assets/theme/theme-blue-grey.scss' hide $colors;
> @import 'primeng/resources/primeng.min.css';
> @import 'primeflex/primeflex.scss';
> @import 'primeicons/primeicons.css';
> 
> /* your other imports */
> ...
> ```

Hey, it seems to work this way. Is this going to be the recommended way? Or is it just a temp fix?

**Comment by mertsincan** [comment]
This is related to https://github.com/primefaces/primeflex/issues/62. So, we'll decide and get back to you. But, the solution above is one recommended by us.
