### ISSUE TITLE
Grid System Docs

### ISSUE THREAD

**Issue by minzdrav** [primefaces/primeflex#94]
Hi PrimeFlex team
Could you please fix Grid System docs? Right now, https://www.primefaces.org/primeflex/gridsystem page contains lorum ipsum instead of real description.
![image](https://user-images.githubusercontent.com/1764392/151142454-cd0353b3-de89-4a9c-8777-50b544bf21d8.png)

**Comment by mertsincan** [comment]
Fixed now! Thanks a lot!
