### ISSUE TITLE
text-color no red color available 

### ISSUE THREAD

**Issue by ahmedabdelhafez** [primefaces/primeflex#95]
Hello dears:
there are no red colors available why, and how to add one for text and bg-color

Thanks.

**Comment by melloware** [comment]
Agreed it looks like RED is missing from the Theme Designer SASS that generates all these colors.

**Comment by ahmedabdelhafez** [comment]
yes, that is right i hope it's fixed to use it in next apps , thanks prime ng team

**Comment by HaasStefan** [comment]
Has anyone got a clean workaround to have some custom red css vars?

**Comment by mycahmason** [comment]
+1

**Comment by melloware** [comment]
This was fixed with this issue: https://github.com/primefaces/primeflex/issues/113

Please close this ticket

**Comment by mertsincan** [comment]
Yes, fixed for the next version.
