### ISSUE TITLE
Data Table issue on v 7.2

### ISSUE THREAD

**Issue by Magvin** [primefaces/primeflex#96]
Seems when we are using Stack as responsive Layout it's not longer responsive

![image](https://user-images.githubusercontent.com/23562296/151965517-3b9e9119-2f04-4a5e-aeaa-3b0efe821cfe.png)

versus old version

![image](https://user-images.githubusercontent.com/23562296/151965596-2081a39b-21b8-48d3-82ba-42e259f01607.png)

**Comment by melloware** [comment]
@Magvin already reported at PrimeReact: https://github.com/primefaces/primereact/issues/2594
