### ISSUE TITLE
NPM configuration incorrect?

### ISSUE THREAD

**Issue by gbdubs** [primefaces/primeflex#98]
Running `npm install primeflex --save` returns the following error, indicating that the NPM configuration for this package is pointing to a nonexistent tarball:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://packagecloud.io/github/git-lfs/npm/primeflex/-/primeflex-3.1.1.tgz
npm ERR! 404 
npm ERR! 404  'primeflex@https://packagecloud.io/github/git-lfs/npm/primeflex/-/primeflex-3.1.1.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

As a temporary workaround you can download the tarball from [here](https://registry.npmjs.org/primeflex/-/primeflex-3.1.2.tgz) and install it via `npm install ~/local/path/to/tarball`

**Comment by melloware** [comment]
Looks like you have your repo pointed to package cloud and not Npm registry?   Your command works fine for me and brings down Primeflex 3.1.2 no problem.

**Comment by gbdubs** [comment]
You're totally right. Thank you for the correction!

**Comment by gbdubs** [comment]
In case anyone runs into the same issue, this is the solution: 

https://stackoverflow.com/questions/47520181/installing-npm-package-fails-with-404

**Comment by melloware** [comment]
Glad I could help 😁
